version: '2'
services:
  db:
    build: ./db
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/pgdata
  api:
    build: ./api
    ports:
      - "8080:8080"
    links:
      - db
    environment:
      - DB_URI=postgresql://postgres:postgres@db/
